metadata: "data/metadata/metadata.yml"
dorieh-metadata: "data/metadata/dorieh-metadata.yaml"
docker:
  image: "nsaph/zip2zcta_master_xwalk"
  run: $CMD
  output: data/output/zip2zcta_master_xwalk/zip2zcta_master_xwalk.csv
