name: zip2zcta_master_xwalk
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - snakemake=8.1.2
  - hydra-core=1.3.2
  - pandas=2.2.1
  - xlrd=2.0.1
  - openpyxl=3.1.2
  - pyarrow=14.0.2
  - python-duckdb=0.10.2
  - pip=24.0
  - pip:
    - ipykernel==6.29.4
